# Generated by Django 4.1.1 on 2022-09-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=50)),
                ("surname", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("order_number", models.IntegerField()),
                ("feedback", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
    ]
