# Generated by Django 4.1.1 on 2022-09-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_cost",
        ),
        migrations.RemoveField(
            model_name="orderline",
            name="product_price",
        ),
    ]
