# Generated by Django 4.1.1 on 2022-09-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_remove_product_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="photo",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="title",
            new_name="name",
        ),
    ]
